// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/betshark-vibes/AmberVault.tsx": () => import("../components/mockups/betshark-vibes/AmberVault.tsx"),
  "./components/mockups/betshark-vibes/ArcticGlass.tsx": () => import("../components/mockups/betshark-vibes/ArcticGlass.tsx"),
  "./components/mockups/betshark-vibes/NeonNoir.tsx": () => import("../components/mockups/betshark-vibes/NeonNoir.tsx")
};
